// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project.model;

namespace project.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20210217111334_funding")]
    partial class funding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("project.model.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PROJECT_ID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("TITLE");

                    b.HasKey("Id");

                    b.ToTable("PROJECTS");
                });

            modelBuilder.Entity("project.model.Subproject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SUBPROJECT_ID");

                    b.Property<int>("AppliedResearch")
                        .HasColumnType("int")
                        .HasColumnName("APPLIED_RESEARCH");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<int>("FocusResearch")
                        .HasColumnType("int")
                        .HasColumnName("FOCUS_RESEARCH");

                    b.Property<int>("TheoreticalResearcb")
                        .HasColumnType("int")
                        .HasColumnName("THEORETICAL_RESEARCH");

                    b.HasKey("Id");

                    b.ToTable("SUBPROJECT");
                });

            modelBuilder.Entity("project.model.ResearchFundingProject", b =>
                {
                    b.HasBaseType("project.model.Project");

                    b.Property<sbyte>("IsSmallProject")
                        .HasColumnType("TINYINT")
                        .HasColumnName("IS_SMALL_PROJECT");

                    b.ToTable("RESEARCH_FUNDING_PROJECT");
                });

            modelBuilder.Entity("project.model.ResearchFundingProject", b =>
                {
                    b.HasOne("project.model.Project", null)
                        .WithOne()
                        .HasForeignKey("project.model.ResearchFundingProject", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
