// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project.model;

namespace project.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    partial class ProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("project.model.Debitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DEBITOR_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("NAMER");

                    b.HasKey("Id");

                    b.ToTable("DEBITORS");
                });

            modelBuilder.Entity("project.model.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("FACILITY_ID");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("FACILITY_TYPE")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FacilityCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(7)")
                        .HasColumnName("FACILITY_CODE");

                    b.Property<string>("FacilityTitle")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("FACILITY_TITLE");

                    b.HasKey("Id");

                    b.ToTable("FACILITIES");

                    b.HasDiscriminator<string>("FACILITY_TYPE").HasValue("Facility");
                });

            modelBuilder.Entity("project.model.Funding", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("PROJECT_ID");

                    b.Property<int>("DebitorId")
                        .HasColumnType("int")
                        .HasColumnName("DEBITOR_ID");

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(8,2)")
                        .HasColumnName("FUNDING_AMOUNT");

                    b.HasKey("ProjectId", "DebitorId");

                    b.HasIndex("DebitorId");

                    b.ToTable("FUNDING");
                });

            modelBuilder.Entity("project.model.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PROJECT_ID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("LegalFoundation")
                        .IsRequired()
                        .HasColumnType("VARCHAR(4)")
                        .HasColumnName("LEGAL_FOUNDATION");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("TITLE");

                    b.HasKey("Id");

                    b.ToTable("PROJECTS");
                });

            modelBuilder.Entity("project.model.Subproject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SUBPROJECT_ID");

                    b.Property<int>("AppliedResearch")
                        .HasColumnType("int")
                        .HasColumnName("APPLIED_RESEARCH");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<int>("FocusResearch")
                        .HasColumnType("int")
                        .HasColumnName("FOCUS_RESEARCH");

                    b.Property<int?>("InstituteId")
                        .HasColumnType("INT");

                    b.Property<int?>("PROJECT_ID")
                        .HasColumnType("int");

                    b.Property<int>("TheoreticalResearcb")
                        .HasColumnType("int")
                        .HasColumnName("THEORETICAL_RESEARCH");

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.HasIndex("PROJECT_ID");

                    b.ToTable("SUBPROJECT");
                });

            modelBuilder.Entity("project.model.Faculty", b =>
                {
                    b.HasBaseType("project.model.Facility");

                    b.ToTable("FACILITIES");

                    b.HasDiscriminator().HasValue("FACULTY");
                });

            modelBuilder.Entity("project.model.Institute", b =>
                {
                    b.HasBaseType("project.model.Facility");

                    b.ToTable("FACILITIES");

                    b.HasDiscriminator().HasValue("INSTITUTE");
                });

            modelBuilder.Entity("project.model.ResearchFundingProject", b =>
                {
                    b.HasBaseType("project.model.Project");

                    b.Property<sbyte>("IsSmallProject")
                        .HasColumnType("TINYINT")
                        .HasColumnName("IS_SMALL_PROJECT");

                    b.ToTable("RESEARCH_FUNDING_PROJECT");
                });

            modelBuilder.Entity("project.model.Funding", b =>
                {
                    b.HasOne("project.model.Debitor", "Debitor")
                        .WithMany()
                        .HasForeignKey("DebitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("project.model.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Debitor");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("project.model.Subproject", b =>
                {
                    b.HasOne("project.model.Institute", "Institute")
                        .WithMany()
                        .HasForeignKey("InstituteId");

                    b.HasOne("project.model.Project", "Project")
                        .WithMany()
                        .HasForeignKey("PROJECT_ID");

                    b.Navigation("Institute");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("project.model.ResearchFundingProject", b =>
                {
                    b.HasOne("project.model.Project", null)
                        .WithOne()
                        .HasForeignKey("project.model.ResearchFundingProject", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
